version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      development:
        dependency-type: development
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - 'eslint'
          - '@solana/web3.js'
          - 'chainfile-*'
          - '@chainfile/*'
      workspace:
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'prettier-*'
          - 'typescript-eslint'
          - 'globals'
          - '@eslint/*'
          - 'eslint'
          - 'eslint-*'
